# File: .github/workflows/ci.yml
name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install flake8 black pytest pytest-cov
      - run: flake8
      - run: black --check .
      - run: pytest --maxfail=1 --disable-warnings --cov
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
