name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install ROS 2 dependencies
        run: |
          sudo apt update
          sudo apt install -y curl gnupg lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | sudo apt-key add -
          echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list
          sudo apt update
          sudo apt install -y ros-humble-ros-base
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint
        run: flake8
      - name: Format
        run: black --check .
      - name: Tests
        run: pytest --maxfail=1 --disable-warnings --cov
      - name: Upload coverage
        uses: codecov/codecov-action@v3
